### ISSUE TITLE
There is no need to sync

### ISSUE THREAD

**Issue by xczh** [pingcap/log#13] opened 2021-01-08 17:57 UTC
See here: 
https://github.com/pingcap/log/blob/8f1e84a3abc8f75ae33a8bee86d561f21057393e/log.go#L127
```go
// Sync flushes any buffered log entries.
func Sync() error {
	err := L().Sync()
	if err != nil {
		return err
	}
	return S().Sync()
}
```

这里没有必要调用`S().Sync()`，因为 `*SugaredLogger.Sync()` 的实现如下：

There is no need to call `S().Sync()` because `*SugaredLogger.Sync()` which is implemented as:

```go
type SugaredLogger struct {
	base *Logger
}

// Sync flushes any buffered log entries.
func (s *SugaredLogger) Sync() error {
	return s.base.Sync()
}
```

因此，这和已经调用的`L().Sync()`等价，`SugaredLogger`没有独立的`Sync()`方法，它依赖于`Logger`的`Sync()`。

It's equivalent to `L().Sync()`, which has been called.

**Comment by tisonkun** [comment] 2021-06-14 09:17
Not really. The base logger of SugaredLogger is a clone of original Logger. See

```go
func (log *Logger) Sugar() *SugaredLogger {
	core := log.clone()
	core.callerSkip += 2
	return &SugaredLogger{core}
}

func (log *Logger) clone() *Logger {
	copy := *log
	return &copy
}
```

**Comment by tisonkun** [comment] 2021-08-18 15:00
closed as not a bug

**Closed by tisonkun** 2021-08-18 15:00 UTC
